'use client';
import { useState } from 'react';
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001';
type Appointment = { referenceCode: string; startsAt: string; status: string; doctor: { name: string } };
export function AppointmentLookup() {
  const [referenceCode, setReferenceCode] = useState(''); const [phoneLast4, setPhoneLast4] = useState(''); const [appointment, setAppointment] = useState<Appointment | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  async function lookup() { setLoading(true); setMessage(''); setAppointment(null); try { const response = await fetch(`${apiUrl}/api/appointments/${encodeURIComponent(referenceCode)}?phoneLast4=${encodeURIComponent(phoneLast4)}`); const data = await response.json() as Appointment & { error?: string }; if (!response.ok) throw new Error(data.error ?? '查無預約資料。'); setAppointment(data); } catch (error) { setMessage(error instanceof Error ? error.message : '查詢失敗。'); } finally { setLoading(false); } }
  async function cancel() { if (!appointment || !confirm('確定要取消此預約嗎？')) return; setLoading(true); setMessage(''); try { const response = await fetch(`${apiUrl}/api/appointments/${encodeURIComponent(appointment.referenceCode)}/cancel`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phoneLast4 }) }); const data = await response.json() as Appointment & { error?: string }; if (!response.ok) throw new Error(data.error ?? '取消失敗。'); setAppointment(data); setMessage('預約已取消。'); } catch (error) { setMessage(error instanceof Error ? error.message : '取消失敗。'); } finally { setLoading(false); } }
  const date = appointment && new Intl.DateTimeFormat('zh-TW', { timeZone: 'Asia/Taipei', dateStyle: 'full', timeStyle: 'short', hour12: false }).format(new Date(appointment.startsAt));
  return <section className="mt-8 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="space-y-4"><label className="block text-sm font-medium">預約編號<input value={referenceCode} onChange={(event) => setReferenceCode(event.target.value.toUpperCase())} placeholder="DC-XXXXXXXX" className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">手機末四碼<input inputMode="numeric" maxLength={4} value={phoneLast4} onChange={(event) => setPhoneLast4(event.target.value.replace(/\D/g, ''))} placeholder="1234" className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2" /></label><button type="button" disabled={loading || !referenceCode || phoneLast4.length !== 4} onClick={lookup} className="rounded-lg bg-sky-600 px-5 py-2.5 font-medium text-white disabled:opacity-50">{loading ? '處理中⋯' : '查詢預約'}</button></div>{appointment && <div className="mt-6 rounded-xl bg-slate-50 p-4 text-sm leading-7"><p><strong>預約編號：</strong>{appointment.referenceCode}</p><p><strong>醫師：</strong>{appointment.doctor.name}</p><p><strong>時段：</strong>{date}</p><p><strong>狀態：</strong>{appointment.status === 'CANCELLED' ? '已取消' : '已預約'}</p>{appointment.status !== 'CANCELLED' && <button type="button" disabled={loading} onClick={cancel} className="mt-3 rounded-lg border border-red-300 px-4 py-2 text-red-700 disabled:opacity-50">取消預約</button>}<p className="mt-3 text-xs text-slate-500">僅能取消 24 小時後的預約。</p></div>}{message && <p role="status" className="mt-5 rounded-lg bg-slate-100 p-3 text-sm text-slate-700">{message}</p>}</section>;
}
