apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dental-clinic
resources:
  - ../../autoscaling
  - postgres.yaml
  - gateway.yaml
images:
  - name: ghcr.io/48124812/dental-clinic-api
    newTag: sha-0d8a1757a0232add134dc407f490eafb6e6f1441
  - name: ghcr.io/48124812/dental-clinic-web
    newTag: sha-0d8a1757a0232add134dc407f490eafb6e6f1441
configMapGenerator:
  - name: lab-gateway-config
    files:
      - default.conf
