'use client';
import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001';
const today = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Taipei' });
type Item = { id: string; referenceCode: string; startsAt: string; patientName: string; patientPhone: string; status: string; doctor: { name: string } };
export function StaffAppointmentDashboard() {
  const router = useRouter(); const params = useSearchParams(); const [token, setToken] = useState(() => typeof window === 'undefined' ? '' : sessionStorage.getItem('staff-dashboard-token') ?? ''); const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const date = params.get('date') ?? today;
  async function load(activeToken = token) { setLoading(true); setError(''); try { const response = await fetch(`${apiUrl}/api/staff/appointments?date=${date}`, { headers: { Authorization: `Bearer ${activeToken}` } }); const data = await response.json() as Item[] & { error?: string }; if (!response.ok) throw new Error(data.error ?? '讀取預約失敗。'); setItems(data); } catch (reason) { setError(reason instanceof Error ? reason.message : '讀取預約失敗。'); } finally { setLoading(false); } }
  function signIn() { sessionStorage.setItem('staff-dashboard-token', token); void load(token); }
  async function mark(id: string, status: 'CHECKED_IN' | 'NO_SHOW') { const response = await fetch(`${apiUrl}/api/staff/appointments/${id}/status`, { method: 'PATCH', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); if (!response.ok) { const data = await response.json() as { error?: string }; setError(data.error ?? '更新失敗。'); return; } const changed = await response.json() as Item; setItems((current) => current.map((item) => item.id === id ? changed : item)); }
  function changeDate(value: string) { router.replace(`/staff/appointments?date=${value}`); }
  const format = (value: string) => new Intl.DateTimeFormat('zh-TW', { timeZone: 'Asia/Taipei', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value));
  return <section className="mt-8 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap items-end gap-3"><label className="block text-sm font-medium">員工存取 token<input type="password" value={token} onChange={(event) => setToken(event.target.value)} className="mt-1 block w-80 max-w-full rounded-lg border border-slate-300 px-3 py-2" /></label><button type="button" onClick={signIn} disabled={!token || loading} className="rounded-lg bg-sky-600 px-4 py-2 text-white disabled:opacity-50">登入並載入</button><label className="block text-sm font-medium">日期<input type="date" value={date} onChange={(event) => changeDate(event.target.value)} className="mt-1 block rounded-lg border border-slate-300 px-3 py-2" /></label></div>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{token && <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="p-3">時間</th><th className="p-3">病患</th><th className="p-3">醫師</th><th className="p-3">狀態</th><th className="p-3">操作</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b"><td className="p-3">{format(item.startsAt)}</td><td className="p-3">{item.patientName}<span className="block text-xs text-slate-500">{item.patientPhone}</span></td><td className="p-3">{item.doctor.name}</td><td className="p-3">{item.status === 'BOOKED' ? '待到診' : item.status === 'CHECKED_IN' ? '已到診' : item.status === 'NO_SHOW' ? '未到' : '已取消'}</td><td className="p-3">{item.status === 'BOOKED' && <span className="flex gap-2"><button type="button" onClick={() => void mark(item.id, 'CHECKED_IN')} className="rounded border border-emerald-300 px-2 py-1 text-emerald-700">已到</button><button type="button" onClick={() => void mark(item.id, 'NO_SHOW')} className="rounded border border-amber-300 px-2 py-1 text-amber-700">未到</button></span>}</td></tr>)}</tbody></table>{!loading && items.length === 0 && <p className="py-6 text-slate-500">此日期沒有預約。</p>}</div>}</section>;
}
