import { timingSafeEqual } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { config } from '../config.js';
import { prisma } from '../lib/prisma.js';

const image = z.string().refine((value) => !value || (value.length <= 2_800_000 && /^data:image\/(jpeg|png|webp);base64,/.test(value)), 'Image must be JPEG, PNG, or WebP and at most 2MB.');
const doctorSchema = z.object({ name: z.string().min(2).max(80), title: z.string().min(2).max(80), specialties: z.array(z.string().min(1).max(40)).min(1).max(8), bioMd: z.string().min(10).max(4000), credentials: z.array(z.string().min(1).max(120)).min(1).max(12), photoUrl: image.nullable(), displayOrder: z.number().int().min(0).max(999), active: z.boolean() });
const serviceSchema = z.object({ name: z.string().min(2).max(100), category: z.enum(['PREVENTIVE', 'RESTORATIVE', 'COSMETIC', 'ORTHODONTIC', 'SURGERY', 'PEDIATRIC']), priceMin: z.number().int().min(0).max(2_000_000), priceMax: z.number().int().min(0).max(2_000_000).nullable(), isNhi: z.boolean(), descriptionMd: z.string().min(10).max(4000), displayOrder: z.number().int().min(0).max(999), active: z.boolean() });
function invalid(reply: { code: (value: number) => { send: (body: { error: string }) => unknown } }, parsed: z.SafeParseError<unknown>) { return reply.code(400).send({ error: parsed.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; ') }); }
function auth(header?: string) { const [scheme, token] = header?.split(' ') ?? []; const expected = config.ADMIN_DASHBOARD_TOKEN; if (!expected || scheme !== 'Bearer' || !token) return false; const a = Buffer.from(token), b = Buffer.from(expected); return a.length === b.length && timingSafeEqual(a, b); }
async function actor() { return prisma.user.upsert({ where: { email: config.ADMIN_EMAIL }, update: { role: 'ADMIN' }, create: { email: config.ADMIN_EMAIL, passwordHash: 'environment-token-managed', role: 'ADMIN' } }); }
export async function adminCatalogRoutes(app: FastifyInstance) {
  app.addHook('onRequest', async (request, reply) => { if (!auth(request.headers.authorization)) return reply.code(401).send({ error: 'Admin authentication required.' }); });
  app.get('/api/admin/doctors', () => prisma.doctor.findMany({ orderBy: { displayOrder: 'asc' } }));
  app.post('/api/admin/doctors', async (request, reply) => { const parsed = doctorSchema.safeParse(request.body); if (!parsed.success) return invalid(reply, parsed); const user = await actor(); const item = await prisma.doctor.create({ data: parsed.data }); await prisma.auditLog.create({ data: { actorId: user.id, action: 'DOCTOR_CREATED', entityType: 'Doctor', entityId: item.id, after: parsed.data } }); return reply.code(201).send(item); });
  app.put<{ Params: { id: string } }>('/api/admin/doctors/:id', async (request, reply) => { const parsed = doctorSchema.safeParse(request.body); if (!parsed.success) return invalid(reply, parsed); const before = await prisma.doctor.findUnique({ where: { id: request.params.id } }); if (!before) return reply.code(404).send({ error: 'Doctor not found.' }); const user = await actor(); const item = await prisma.doctor.update({ where: { id: before.id }, data: parsed.data }); await prisma.auditLog.create({ data: { actorId: user.id, action: 'DOCTOR_UPDATED', entityType: 'Doctor', entityId: item.id, before: before as never, after: parsed.data } }); return item; });
  app.get('/api/admin/services', () => prisma.service.findMany({ orderBy: { displayOrder: 'asc' } }));
  app.post('/api/admin/services', async (request, reply) => { const parsed = serviceSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'Invalid service.', details: parsed.error.flatten() }); const user = await actor(); const item = await prisma.service.create({ data: parsed.data }); await prisma.auditLog.create({ data: { actorId: user.id, action: 'SERVICE_CREATED', entityType: 'Service', entityId: item.id, after: parsed.data } }); return reply.code(201).send(item); });
  app.put<{ Params: { id: string } }>('/api/admin/services/:id', async (request, reply) => { const parsed = serviceSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: 'Invalid service.', details: parsed.error.flatten() }); const before = await prisma.service.findUnique({ where: { id: request.params.id } }); if (!before) return reply.code(404).send({ error: 'Service not found.' }); const user = await actor(); const item = await prisma.service.update({ where: { id: before.id }, data: parsed.data }); await prisma.auditLog.create({ data: { actorId: user.id, action: 'SERVICE_UPDATED', entityType: 'Service', entityId: item.id, before: before as never, after: parsed.data } }); return item; });
}
