apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  PORT: "3001"
  HOST: "0.0.0.0"
  NODE_ENV: production
  LOG_LEVEL: info
  APP_VERSION: kubernetes
  RUN_MIGRATIONS: "false"
  RUN_SAMPLE_SEED: "false"
